"""1.1.1

Revision ID: 407e6071e7ca
Revises: 720a6289a697
Create Date: 2023-02-17 15:23:21.426571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407e6071e7ca'
down_revision = '720a6289a697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DOUBAN_MEDIAS', sa.Column('MARK_DATE', sa.Text(), nullable=True))
    op.add_column('RSS_TV_EPISODES', sa.Column('EPISODE_FILTER_ORDERS', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RSS_TV_EPISODES', 'EPISODE_FILTER_ORDERS')
    op.drop_column('DOUBAN_MEDIAS', 'MARK_DATE')
    # ### end Alembic commands ###
