"""1.1.2

Revision ID: 4d3747aa9f68
Revises: a3cac67a38d4 
Create Date: 2023-02-13 23:59:14.357722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3747aa9f68'
down_revision = 'a3cac67a38d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DOUBAN_MEDIAS', sa.Column('MARK_DATE', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DOUBAN_MEDIAS', 'MARK_DATE')
    # ### end Alembic commands ###
