"""1.1.1

Revision ID: a3cac67a38d4
Revises: 720a6289a697
Create Date: 2023-02-12 18:11:36.514360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cac67a38d4'
down_revision = '720a6289a697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DOWNLOAD_HISTORY', sa.Column('TORRENT_HASH', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DOWNLOAD_HISTORY', 'TORRENT_HASH')
    # ### end Alembic commands ###
