"""1.1.3

Revision ID: d8bc82e80ac8
Revises: 720a6289a697
Create Date: 2023-02-16 13:27:43.491662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bc82e80ac8'
down_revision = '720a6289a697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RSS_TV_EPISODES', sa.Column('EPISODE_FILTER_ORDERS', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RSS_TV_EPISODES', 'EPISODE_FILTER_ORDERS')
    # ### end Alembic commands ###
